### PR TITLE
hotfix stun code

### LINKED ISSUE #180: STUN DNS query fails are not handled
The error should be caught and HoprConnect should choose a different external STUN server

```
Last 5 logs:
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'stun.counterpath.net'
}
```

### PR DESCRIPTION
**Pull request by robertkiel**
Fixes:
- do not fail on DNS failures during STUN requests to external STUN servers
- properly recover console.log when handling STUN requests
- fail early if no STUN server is reachable

Fixes #180

### CODE REVIEW

File: src/stun.ts [hunk 1]
```diff
@@ -115,67 +143,71 @@ export function getExternalIp(
       tids.splice(index, 1)
       const attr = res.getXorMappedAddressAttribute() ?? res.getMappedAddressAttribute()
 
+      console.log = backup
```
Comment (tolbrino) [inline src/stun.ts:146]: The variable `backup` needs a better name.

File: src/listener.ts [hunk 2]
```diff
@@ -359,7 +359,11 @@ class Listener extends EventEmitter implements InterfaceListener {
             return cOpts.host !== host || cOpts.port !== port
           })
 
-    this.externalAddress = await getExternalIp(usableStunServers, this.udpSocket)
+    try {
+      this.externalAddress = await getExternalIp(usableStunServers, this.udpSocket)
+    } catch (err) {
+      error(err.message)
```
Comment (tolbrino) [inline src/listener.ts:365]: Why is this better than letting the exception run its course?

File: src/stun.spec.ts [hunk 3]
```diff
@@ -9,25 +9,28 @@ import { once } from 'events'
...
-      server.on('message', (msg: Buffer, rinfo: RemoteInfo) => handleStunRequest(server, msg, rinfo))
-      server.on('error', (e) => {
-        throw e
-      })
-      return server
-    })
-  })
+  before(async () => {
+    servers = await Promise.all(
+      Array.from({ length: 4 }).map(
```
Comment (tolbrino) [inline src/stun.spec.ts:14]: any reason for the test size of 4?

File: src/stun.ts [hunk 4]
```diff
@@ -115,67 +143,71 @@ export function getExternalIp(
...
+    const allSent = performStunRequests(usableMultiaddrs, tids, socket)
 
-      const nodeAddress = ma.nodeAddress()
+    if (allSent.length > 0) {
+      const sendResults = await Promise.all(allSent)
 
-      const res = stun.createBindingRequest(tids[index]).setFingerprintAttribute()
-
-      verbose(`STUN request sent to ${nodeAddress.address}:${nodeAddress.port}`)
+      if (!sendResults.some((result) => result)) {
```
Comment (tolbrino) [inline src/stun.ts:167]: Better variable naming would indicate what is going on here:

```suggestion
      if (!sendResults.some((requestOk: boolean) => requestOk)) {
```

File: src/listener.ts (hunk 2 above)
Comment (robertkiel) [reply src/listener.ts:365]: Currently, it's not properly defined. The idea is to automatically fallback to "not getting a STUN response", hence no external address known, and then log the error message

File: src/stun.ts (hunk 1 above)
Comment (robertkiel) [reply src/stun.ts:146]: changed

File: src/stun.spec.ts (hunk 3 above)
Comment (robertkiel) [reply src/stun.spec.ts:14]: The idea is to start a few STUN servers and test against each other. Need to checkout if 4 is a good choice. Have changed the tests multiple times

File: src/stun.ts (hunk 4 above)
Comment (robertkiel) [reply src/stun.ts:167]: changed
